name: Documentation

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: docs/package-lock.json
        
    - run: npm ci
      working-directory: docs
      name: Restore dependencies
  
    - run: npm run build
      working-directory: docs
      name: Build documentation
        
    - name: Archive documentation
      uses: actions/upload-artifact@v3
      with:
        name: Documentation
        path: docs/build/
